- .circleci/config.yml
- .codecov.yml
- .golangci.yml
- README.md
> CI improvements

- README.md
- app/app.go
- app/init.go
- app/init_test.go
- cmd/desmoscli/main.go
- cmd/desmosd/main.go
- cmd/desmoskeyutil/main.go
- Changed the default staking bond denom to desmos by default (closes #25).  
- Changed the README to remove the indication of changing the `genesis.json` file
- Run `goimports` and `gofmt` on the overall project files
> Default bond denom  changes

- docs/developers/queries/posts.md
- x/posts/alias.go
- x/posts/client/cli/keys.go
- x/posts/client/cli/query.go
- x/posts/client/rest/query.go
- x/posts/internal/keeper/keeper.go
- x/posts/internal/keeper/keeper_test.go
- x/posts/internal/types/post_sorting.go
- x/posts/internal/types/querier.go
Added the support for `sort` and `sort-order` flags inside the posts query. Closes #78.
> Added the support for sorting inside the posts query

- Makefile
- cmd/desmosd/testnet.go
- docker-compose.yml
- x/posts/internal/keeper/alias_functions.go
- x/posts/internal/keeper/alias_functions_test.go
- x/posts/internal/keeper/handler.go
- x/posts/internal/keeper/handler_test.go
- x/posts/internal/types/post.go
- x/posts/legacy/v0.2.0/types.go
- x/posts/legacy/v0.3.0/migrate.go
- x/posts/legacy/v0.3.0/migrate_test.go
…s well as the squashing of jumping post ids
This PR improves the v0.3.0 migration by adding the removal of double posts as well as the squashing of jumping post ids. Closes #100.
> v0.3.0 migration improvements

- docs/validators/update.md
Changed `systemctly` to `systemctl`
> Fixed a mistake in one of the commands

- x/posts/legacy/v0.4.0/migrate.go
- x/posts/legacy/v0.4.0/migrate_test.go
This PR add some missing tests for the functions used by the `v0.4.0` migrate.
> Added migrate functions tests

- CHANGELOG.md
- x/genutil/client/cli/migrate.go
- x/genutil/legacy/v0.5.0/migrate.go
- x/posts/legacy/v0.5.0/migrate.go
- x/posts/legacy/v0.5.0/migrate_test.go
> Migrate v050 implementation

- cli_test/cli_posts_test.go
- x/magpie/alias.go
- x/posts/alias.go
- x/posts/internal/types/alias.go
- x/posts/internal/types/models/alias.go
- x/posts/internal/types/models/post_response.go
- x/profile/alias.go
Fixes some tests that are currently failing on `master`.
> Tests fixes

- cli_test/cli_posts_test.go
- docs/.vuepress/config.js
- docs/fullnode/installation.md
- docs/fullnode/rocksdb-installation.md
- x/magpie/alias.go
- x/posts/alias.go
- x/posts/internal/types/alias.go
- x/posts/internal/types/models/alias.go
- x/posts/internal/types/models/post_response.go
- x/profile/alias.go
Improved the documentation on how to use RocksDB when setting up the node
> Docs improvements

- CHANGELOG.md
- x/magpie/internal/keeper/handler.go
- x/posts/internal/keeper/handler.go
- x/posts/internal/keeper/handler_test.go
- x/profile/internal/keeper/handler.go
- x/profile/internal/keeper/handler_test.go
This PR fixed the currently incorrect usage of on-chain events (closes #175).
> Chain events improvements

- CHANGELOG.md
- go.mod
This PR updated the Cosmos SDK dependency to `v0.38.4`. Fixes #177
> Updated Cosmos to v0.38.4

- CHANGELOG.md
- app/app.go
- app/sim_test.go
- cli_test/cli_test.go
- x/posts/internal/simulation/operations.go
- x/profile/internal/simulation/operations.go
- x/reports/internal/simulation/operations.go
This PR restore gov module and its tests + fix the tests that didn't work on the PR #184.
Closes #173.
> Gov module restore and tests fixes

- CHANGELOG.md
- x/posts/internal/keeper/handler.go
- x/posts/internal/keeper/handler_test.go
- x/profiles/internal/keeper/handler.go
- x/profiles/internal/keeper/handler_test.go
- x/profiles/internal/types/events.go
- x/profiles/internal/types/profile.go
- x/profiles/internal/types/profile_test.go
- Formatted time using the Format method (closes #211)
- Added the profile creation date to the save event (closes #210)
- Improved the profile Equals method and its tests
> Multiple improvements

- CHANGELOG.md
- docs/developers/queries/params.md
- x/posts/client/cli/query.go
- x/posts/client/rest/query.go
This PR rename posts parameters queries endpoint.
Closes #245 .
> Post parameters queries endpoint renamed

- CHANGELOG.md
- docs/developers/queries/params.md
- x/profiles/client/cli/query.go
- x/profiles/client/rest/query.go
This PR take care of fixing the errors of profiles' parameters REST queries.
Closes  #244 .
> Profile parameters queries endpoint FIX

- CHANGELOG.md
> Prepare for Desmos v0.10.0

- CHANGELOG.md
Fixed the CHANGELOG formatting
> Updated the CHANGELOG

- .github/workflows/test.yml
- CHANGELOG.md
- cli_test/cli_posts_test.go
- cli_test/cli_profile_test.go
- x/posts/types/models/post_test.go
- x/profiles/keeper/handler.go
- x/profiles/keeper/handler_test.go
- x/profiles/types/models/profile.go
- x/profiles/types/models/profile_test.go
This PR make a small edit inside `profiles` workflow to allow users to change their DTag.
Closes #226.
> Allow users to change their DTag

- CHANGELOG.md
- docs/validators/validator-faq.md
- x/posts/keeper/legacy/v0.10.0/types.go
This PR implements version 0.12.1 which fixes a migration bug that occurred in 0.12.0.
> Version 0.12.1

- contrib/validators/automatic-fullnode-installer.sh
This PR updates the full node installation script to work properly with Desmos v0.12.2
> Documentation update for v0.12.2

- contrib/validators/automatic-fullnode-installer.sh
- docs/fullnode/setup/overview.md
- docs/validators/setup.md
> Fixed automatic full node installation

- contrib/validators/automatic-fullnode-installer.sh
Signed-off-by: riccardo.montagnin <riccardo.montagnin@gmail.com>
> Fixed installer

- contrib/validators/automatic-fullnode-installer.sh
This PR fixes the installation script making so that Desmos is built locally on the machine instead of downloaded through IPFS. This makes the script compatible with all the architectures properly.
> Fixed installation script

- CHANGELOG.md
- x/posts/types/alias.go
- x/posts/types/models/alias.go
- x/profiles/types/alias.go
- x/relationships/alias.go
- x/relationships/types/alias.go
- x/relationships/types/events.go
- x/reports/types/alias.go
- x/reports/types/models/alias.go
This PR removes the user_block event attribute prefix.
Closes #291 .
> Removed user_block event attribute key prefix

- CHANGELOG.md
- cli_test/cli_relationships_test.go
- cli_test/test_helpers.go
- docs/fullnode/setup/overview.md
- x/posts/keeper/common_functions_test.go
- x/posts/keeper/keeper_test.go
- x/posts/types/models/post_test.go
- x/posts/types/msgs/msgs_test.go
- x/relationships/client/cli/query.go
This PR solves the bug inside `desmoscli q relationships all` bug, closes #306.
> Relationships query fix

- .github/workflows/test.yml
- Makefile
- docs/fullnode/setup/overview.md
This PR fixes the integration tests from not working. The problem was actually the [default timeout of Go tests](https://golang.org/cmd/go/#hdr-Testing_flags) which was capped to 10 minutes, not enough time to execute them all.
To fix it, I've added a 20 minutes timeout to the integration tests by using `-timeout 20m`.
> Fixing integration tests

- x/genutil/client/cli/migrate.go
- x/genutil/legacy/v0.13.0/migrate_test.go
- x/genutil/legacy/v0.15.0/migrate.go
- x/genutil/legacy/v0.15.0/migrate_test.go
- x/posts/legacy/v0.13.0/types.go
- x/posts/legacy/v0.15.0/migrate.go
- x/posts/legacy/v0.15.0/migrate_test.go
- x/posts/legacy/v0.15.0/types.go
- x/posts/types/genesis.pb.go
- x/posts/types/query.pb.go
- x/profiles/legacy/v0.13.0/types.go
- x/profiles/legacy/v0.15.0/migrate.go
- x/profiles/legacy/v0.15.0/migrate_test.go
- x/profiles/legacy/v0.15.0/types.go
- x/relationships/legacy/v0.13.0/types.go
- x/relationships/legacy/v0.15.0/migrate.go
- x/relationships/legacy/v0.15.0/migrate_test.go
- x/relationships/legacy/v0.15.0/types.go
- x/reports/legacy/v0.13.0/types.go
- x/reports/legacy/v0.15.0/migrate.go
- x/reports/legacy/v0.15.0/migrate_test.go
- x/reports/legacy/v0.15.0/types.go
- x/reports/types/models.pb.go
- x/reports/types/msgs.pb.go
- x/reports/types/query.pb.go
This PR contains the migration of all our modules from the `v0.14`(even `v0.13`) to the version `v0.15`.
I written but commented the integration test for migration cause we need first to migrate from `v0.12.2`to `v0.13.0`.
> Stargate migration

- x/posts/module.go
- x/profiles/module.go
- x/reports/module.go
Signed-off-by: riccardo.montagnin <riccardo.montagnin@gmail.com>
> Fixed init genesis methods

- .github/workflows/docs.yml
- docs/developers/msgs/edit_param_proposal.md
- docs/developers/msgs/magpie/create-session.md
- docs/developers/msgs/posts/add-post-reaction.md
- docs/developers/msgs/posts/answer-poll.md
- docs/developers/msgs/posts/create-post.md
- docs/developers/msgs/posts/edit-post.md
- docs/developers/msgs/posts/register-reaction.md
- docs/developers/msgs/posts/remove-post-reaction.md
- docs/developers/msgs/profiles/accept-dtag-transfer-request.md
- docs/developers/msgs/profiles/cancel-dtag-transfer-request.md
- docs/developers/msgs/profiles/delete-profile.md
- docs/developers/msgs/profiles/refuse-dtag-transfer-request.md
- docs/developers/msgs/profiles/request-dtag-transfer.md
- docs/developers/msgs/profiles/save-profile.md
- docs/developers/msgs/relationships/block-user.md
- docs/developers/msgs/relationships/create-relationship.md
- docs/developers/msgs/relationships/delete-relationship.md
- docs/developers/msgs/relationships/unblock-user.md
- docs/developers/msgs/reports/report-post.md
- docs/validators/kms/kms.md
- docs/validators/kms/kms_ledger.md
Updated the documentation of the messages, and fixed the docs workflow
> Docs fixes

- docs/fullnode/overview.md
- docs/fullnode/setup.md
Updated the fullnode setup documentation
> Updated the fullnode setup documentation

- docs/validators/common-problems.md
Improved jailed problem solution inside the docs
> Improved the jailed solution

- CHANGELOG.md
- Makefile
This PR adds the Tendermint LD flag to the Makefile, closing #360
> Added Tendermint LD flag

- CHANGELOG.md
- go.mod
- go.sum
This PR updates Cosmos to v0.41.3, closing #359
> Updated Cosmos to v0.41.3

- .github/workflows/test.yml
- CHANGELOG.md
- Makefile
This PR adds the support for ARM-32 platform by: 
- adding a `make build-arm` command
- adding build tests to make sure the compatibility is not broken in the future
> ARM-32 support

- CHANGELOG.md
> Version 0.15.2

- CHANGELOG.md
> Version 0.15.3

- docs/validators/setup.md
- package-lock.json
- package.json
Fixes some minor error in the doc.
> update how to confirm validator is running

- .github/workflows/test.yml
- CHANGELOG.md
- app/app.go
- app/app_test.go
- go.mod
- go.sum
Signed-off-by: riccardo.montagnin <riccardo.montagnin@gmail.com>
This PR updates Cosmos to v0.42.1 and fixes a security vulnerability
> Updated Cosmos to v0.42.1

- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/proto.yml
- .github/workflows/release.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- x/relationships/legacy/v0.15.0/migrate_test.go
This PR improves the GitHub workflow names and also fixes a race test
> Improving tests

- .github/workflows/docs.yml
- docs/.vuepress/config.js
- docs/README.md
- docs/testnets/apollo.md
- go.mod
This PR adds the documentation required in order to tell people how they can participate in the upcoming `morpheus-apollo-1` testnet.
> Docs for morpheus-apollo-1

- docs/testnets/apollo.md
Updated validator key file name and added some notes for gentx.
> update docs for morpheus-apollo-1

- docs/testnets/apollo.md
Added some commands to the docs.
> Added keys command to the docs

- app/app.go
This PR reintroduce the `x/mint` cosmos module that we need in order to test inflation inside `Apollo`.
Close #394.
> add mint module to app

- CHANGELOG.md
Signed-off-by: riccardo.montagnin <riccardo.montagnin@gmail.com>
Updated Changelog
> Version v0.16.0

- CHANGELOG.md
> Version 0.16.1

- CHANGELOG.md
- x/profiles/client/cli/cli_test.go
- x/profiles/client/cli/tx.go
This PR solves some bug I found while playing with `profiles` related operations inside Apollo.
Closes #407 #408 #409.
> Profiles modules bug fixes

- CHANGELOG.md
- app/app.go
- go.mod
- go.sum
This PR updates the Cosmos SDK version we are using to point towards a custom branch made inside the [desmos-labs/cosmos-sdk](https://github.com/desmos-labs/cosmos-sdk) fork that I've made.
I've updated the fork to also include the cosmos-sdk#8865 fix for vesting accounts, which should fix #384.
I've also added inside the `app.go` file an example of how a migration should be set to update the currently running `morpheus-apollo-1` testnet using the `x/upgrade` module.
> Updated Cosmos SDK to fix vesting accounts

- CHANGELOG.md
- docs/developers/types/profiles/profile.md
- x/profiles/keeper/msgs_server.go
- x/profiles/keeper/msgs_server_test.go
- x/profiles/types/common/common_functions.go
- x/profiles/types/events.go
- x/staging/posts/types/events.go
This PR solves small stuff like the attribute renaming, the update regEx for docs.
Closes #423.
Closes #424.
Closes #425.
> Small fixes

- CHANGELOG.md
- app/app.go
Signed-off-by: Riccardo Montagnin <riccardo.montagnin@gmail.com>
Fixes #421
> Added missing community spend proposal handler

- CHANGELOG.md
- app/desmos/cmd/root.go
- go.mod
- x/staging/posts/keeper/keeper_reports.go
- x/staging/posts/types/report_test.go
This PR prepares the files for the new `v0.16.3` tag
> Version 0.16.3

- docs/fullnode/cosmovisor.md
This PR updated the documentation to fix some issues inside the Cosmovisor setup
> Updated Cosmovisor docs

- proto/desmos/subspaces/v1beta1/query.proto
- x/staging/subspaces/client/cli/query.go
- x/staging/subspaces/keeper/grpc_query.go
- x/staging/subspaces/keeper/grpc_query_test.go
- x/staging/subspaces/types/query.go
- x/staging/subspaces/types/query.pb.go
- x/staging/subspaces/types/query.pb.gw.go
This PR fixes the Proto lint error by renaming the subspaces queries requests and response types
> Fixed Proto lint errors

- .github/workflows/release.yml
Following the latest upgrade problems, this PR updated the `release` workflow to create zip files or the built binaries automatically
> Release workflow improvements

- docs/validators/kms/kms.md
- docs/validators/kms/kms_softsign.md
Update on KMS docs part and added soft sign guide.
> KMS docs update

- .golangci.yml
- CHANGELOG.md
- go.mod
- go.sum
- x/profiles/keeper/keeper_ibc.go
- x/staging/posts/keeper/keeper_polls_test.go
This PR updates the Cosmos SDK for to version v0.42.6.
Closes #509
> Updated Cosmos to latest version v0.42.6

- docs/developers/types/staging/posts/reaction.md
- go.mod
- go.sum
This PR updates the dependency towards the [`Go-Emoji-Utils`](https://github.com/desmos-labs/go-emoji-utils) library adding new supported emojis. It also fixes the docs checks
> Update emoji support

- testutil/profiles.go
- x/profiles/types/account_test.go
- x/profiles/types/events.go
- x/profiles/types/expected_keeper.go
- x/profiles/types/genesis_test.go
- x/profiles/types/models_app_links_test.go
- x/profiles/types/models_chain_links_test.go
- x/profiles/types/models_dtag_requests_test.go
- x/profiles/types/models_packets_test.go
- x/profiles/types/models_params_test.go
- x/profiles/types/models_profile_test.go
- x/profiles/types/models_relationships.go
- x/profiles/types/models_relationships_test.go
- x/profiles/types/msgs_app_links_test.go
- x/profiles/types/msgs_chain_links_test.go
- x/profiles/types/msgs_dtag_requests_test.go
- x/profiles/types/msgs_profile_test.go
- x/profiles/types/msgs_relationships_test.go
- x/profiles/types/packet.go
This PR improves the tests that are present inside the `x/profiles/types` package following the specifications written inside #481.
> Profiles types test improvements

- testutil/simtesting/utils.go
- x/profiles/simulation/operations_dtag_transfers.go
- x/profiles/simulation/operations_profile.go
- x/profiles/simulation/operations_relationships.go
- x/profiles/simulation/operations_user_blocks.go
This PR improves the simluation tests that are present inside the `x/profiles/simulation` package following the specifications written inside #481.
> Profiles simulation tests improvements

- docs/fullnode/overview.md
- docs/fullnode/setup.md
Recently we updated the docs and ended up duplicating sections regarding snapshots. I removed it and fixed the section numbering
> removed: duplicate snapshot documentation

- docs/.vuepress/config.js
Updated all Docs relative paths to be absolute.
Closes #559
> Fix for docs routing

- docs/developers/msgs/profiles/link-chain-account.md
- docs/developers/msgs/profiles/unlink-chain-account.md
- docs/developers/perform-transactions.md
- docs/developers/types/profiles/chain-link.md
Add docs associated chain link.
Close #589
> Add chain link msg docs

- x/profiles/client/cli/cli_profile.go
> fix: added missing \ in profile save command example

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE/other.md
- .github/dependabot.yml
- .github/labeler.yml
- .github/workflows/docker.yml
- .github/workflows/janitor.yml
- .github/workflows/labeler.yml
- .github/workflows/lint-pr.yml
- .github/workflows/release-sims.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
- STABLE_RELEASES.md
- docs/architecture/PROCESS.md
- docs/architecture/README.md
- docs/architecture/adr-template.md
This PR updates the GitHub actions and contributions docs
> chore: updated actions and contribution docs

- .github/workflows/on-chain-upgrade.yml
Adds a check to the on-chain upgrade GitHub action so that it is run only when the `requires-upgrade` label is set.
---
I have...
I have...
> build: added check to run on-chain-upgrade test only when required

- .github/workflows/on-chain-upgrade.yml
- .github/workflows/test.yml
- .gitignore
- CHANGELOG.md
- Makefile
- app/app.go
- app/desmos/cmd/testnet.go
- contrib/images/Makefile
- contrib/images/desmos-build/Dockerfile
- contrib/images/desmos-cosmovisor/Dockerfile
- contrib/images/desmos-cosmovisor/wrapper.sh
- contrib/images/desmos-env/Dockerfile
- contrib/images/desmos-python/Dockerfile
- contrib/images/desmos-python/requirements.txt
- contrib/upgrade_testnet/docker-compose.yml
- contrib/upgrade_testnet/setup_genesis.py
- contrib/upgrade_testnet/start.sh
- contrib/upgrade_testnet/stop.sh
- contrib/upgrade_testnet/submit_upgrade_proposal.sh
This PR adds an on-chain upgrade handler for the upcoming version `1.0.4`. 
This will be used inside the Morpheus testnet to upgrade it to the same version of the current Desmos mainnet, so that we can later test future mainnet upgrades there as well. 
---
I have...
I have...
> feat: added testnet upgrade handler for v1.0.4

- .changeset/entries/a8161a596e5da05382d96e06bde928bc9f162004ce1acd88b1666ea3e1179832.yaml
- CHANGELOG.md
Prepares version `v2.2.1-testnet`
---
I have...
I have...
> chore: release v2.2.1-testnet

- go.mod
- go.sum
Bumps Cosmos SDK to `v0.44.4`
---
I have...
I have...
> build(deps): bump Cosmos SDK to v0.44.4

- .changeset/entries/ebb2d87b0eb6f008927b013ce828d27ef1af5fddd1f4943ae4d34d6357b82ed1.yaml
- .changeset/entries/fc6dda08613b49d8b7c870c929fc0f026474816d08093146bc8ac6ddf6257f45.yaml
- CHANGELOG.md
This PR prepares the code for release `v2.3.1`
---
I have...
I have...
> chore: release v2.3.1

- .changeset/entries/abe252025d41d256b539f619d25c3a8106d9c10d0e6cd919d7279ecdce4a4166.yaml
- app/app.go
This PR adds the missing `SetVersion` call inside `app.go` which should properly set the server version. 
---
I have...
I have...
> fix: added missing SetVersion method from app

- .mergify.yml
This PR updates the Mergify config to conform to latest changes
---
I have...
I have...
> build: updated Mergify config

- .github/workflows/on-chain-upgrade.yml
- .github/workflows/release.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- Dockerfile
- Dockerfile-ubuntu
- Makefile
- app/sim_test.go
- x/commons/commons.go
- x/subspaces/keeper/genesis.go
- x/subspaces/keeper/genesis_test.go
- x/subspaces/keeper/groups.go
- x/subspaces/keeper/groups_test.go
- x/subspaces/keeper/permissions.go
- x/subspaces/keeper/subspaces.go
- x/subspaces/simulation/genesis.go
- x/subspaces/simulation/operations_permissions.go
- x/subspaces/simulation/operations_subspaces.go
- x/subspaces/simulation/utils.go
This PR fixes the GitHub actions that are currently not executing properly
---
I have...
I have...
> build(ci): fix GitHub actions 

- docs/architecture/adr-008-fee-module.md
Closes: #XXXX
---
I have...
I have...
> docs(adr): ADR-008 Fees module

- go.mod
- go.sum
This reverts commit edbece390d930edd665dda33b76e7c4e3aac128f.
---
I have...
I have...
> revert: bump github.com/tendermint/tendermint from 0.34.16 to 0.34.17 (#804)

- x/supply/keeper/grpc_query_test.go
- x/supply/keeper/keeper_test.go
Fixes currently failing tests on `master`
---
I have...
I have...
> chore: fixed tests

- go.mod
- go.sum
This reverts commit 28b4a2ee2ed2bfacdd7a18bba42933a72d7e90be.
This is due to make sure that `go mod tidy` can work properly on systems that have Go 1.16 or previous installed, which does not work when upgrading `go-ethereum` to `v1.10.17`.
---
I have...
I have...
> revert: bump github.com/ethereum/go-ethereum from 1.10.16 to 1.10.17

- .changeset/entries/d043f6a0d4714847e41f18dd5b2acbd55e0c2fff761d1e0748fd61dcdc9e59b3.yaml
This PR adds the missing changeset entry for PR #812
---
I have...
I have...
> chore: added missing changeset entry for #812

- go.mod
- go.sum
This PR updates our Cosmos SDK fork to `v0.45.3`
---
I have...
I have...
> build(deps): bump github.com/desmos-labs/cosmos-sdk to v0.45.3

- docs/architecture/adr-012-subspaces-sections.md
This PR introduces the concept of subspaces sections, as described inside #856. 
---
I have...
I have...
> docs(adr): ADR-012: Subspaces sections

- .changeset/config.yaml
- .changeset/entries/0b375405b7cd05aced303d5752096b2321d0e60a0559ec4c20e7f538debdb738.yaml
- .changeset/entries/1af1e0e5417d3079d610bae17da72fd728db64762cdb381b4b3da81d5317c102.yaml
- .changeset/entries/2ceedb22572eba8499b4b7abf8c4b38789a979fa8a852a3537dc9cba4b81bc16.yaml
- .changeset/entries/32ba778bad884cf9429f4a0e2d8525170662fa1592a4b25daadc6c9ac4275e2b.yaml
- .changeset/entries/4c0542ccbcb143de87bcd9be2799eb48af7169cec397d425d8fc6d64fe4ca207.yaml
- .changeset/entries/68d07218bf30b0b984be4c29146eb71f915df11721ab81b8eec2595ab493ae4d.yaml
- .changeset/entries/6e78e6f7f9486799935df288f3d1467a646116fddc2952e79e559b1d4cc58d79.yaml
- .changeset/entries/6f0a061bd4ae3038eb8a5a71d9a3b1e6b88397a4e785bda00fec5fbd8bd0737b.yaml
- .changeset/entries/8fea7719728d408975e08ec2ca629f6241c68afe263cc5897d7ebcb0856b4520.yaml
- .changeset/entries/9823041f2fc00cbc264d66d2f4f7b02652004a1296489aa64b6b7b586d6329a5.yaml
- .changeset/entries/bc776b2301982eaae47a6da9ac287a76dace06b0cb1cab882868d56c021dffdc.yaml
- .changeset/entries/d043f6a0d4714847e41f18dd5b2acbd55e0c2fff761d1e0748fd61dcdc9e59b3.yaml
- .changeset/entries/e0e50784a9447e03a4cab7f42c4020754fdb7fc2fabae2a8ce80f15be54561e2.yaml
- .changeset/entries/ed739ae62d392b19a07694f596ae5facae8dbd18ca8eb70bd6be0bc775aee829.yaml
- .changeset/entries/fc7708b5917c157edbbc96281bba1a63928dd2becf8fd057cd3d9592a88f1798.yaml
- CHANGELOG.md
This PR prepares the CHANGELOG for `v3.1.0`
---
I have...
I have...
> chore: release v3.1.0

- x/posts/client/cli/cli_test.go
This PR improves the `x/posts` CLI commands tests by adding some missing test cases from within `CmdCreatePost` tests.
---
I have...
I have...
> chore: improved CmdCreatePost tests

- x/posts/client/cli/cli_test.go
- x/profiles/client/cli/cli_app_links_test.go
- x/profiles/client/cli/cli_chain_links_test.go
- x/profiles/client/cli/cli_dtag_requests_test.go
- x/profiles/client/cli/cli_params_test.go
- x/profiles/client/cli/cli_profile_test.go
- x/profiles/client/cli/cli_test.go
- x/relationships/client/cli/cli_test.go
- x/reports/client/cli/cli_test.go
- x/subspaces/client/cli/cli_test.go
- x/supply/client/cli/cli_test.go
This PR adds the `norace` build tag to CLI tests to make sure they are not run during race condition tests.
---
I have...
I have...
> chore: add norace build tags to CLI tests

- x/profiles/spec/01_concepts.md
- x/profiles/spec/02_state.md
- x/profiles/spec/03_messages.md
- x/profiles/spec/04_events.md
- x/profiles/spec/05_params.md
- x/profiles/spec/06_client.md
- x/profiles/spec/README.md
This PR adds the `spec` folder to the `x/profiles` module, containing the whole specifications. 
Depends-On: #829 
Depends-On: #831
Depends-On: #832
---
I have...
I have...
> docs: DCD-25: add x/profiles spec

- go.mod
- go.sum
This PR reverts desmos-labs/desmos#909 to prevent the following errrors:
```
$ go mod tidy
github.com/desmos-labs/desmos/v3/x/oracle/types imports
gopkg.in/yaml.v2 tested by
gopkg.in/yaml.v2.test imports
gopkg.in/check.v1 loaded from gopkg.in/check.v1@v1.0.0-20200902074654-038fdea0a05b,
but go 1.16 would select v1.0.0-20201130134442-10cb98267c6c
To upgrade to the versions selected by go 1.16:
go mod tidy -go=1.16 && go mod tidy -go=1.17
If reproducibility with go 1.16 is not needed:
go mod tidy -compat=1.17
For other options, see:
https://golang.org/doc/modules/pruning
``` 
---
I have...
*All items are required. Please add a note if the item is not …
> revert: "build(deps): bump github.com/ethereum/go-ethereum from 1.10.18 to 1.10.19"

- .changeset/entries/8e3d1d3f5bce775b80851d2757f6de108f5f76c6636be2235359c8b0c2306ffe.yaml
- .github/workflows/on-chain-upgrade.yml
- app/app.go
- app/upgrades/v400/upgrade.go
- contrib/upgrade_testnet/docker-compose.yml
- x/posts/keeper/migrations.go
- x/posts/legacy/v2/store.go
- x/posts/legacy/v2/store_test.go
- x/reactions/client/cli/tx.go
- x/reactions/keeper/migrations.go
- x/reactions/legacy/v2/store.go
- x/reactions/legacy/v2/store_test.go
- x/reports/client/cli/tx.go
- x/reports/keeper/migrations.go
- x/reports/legacy/v2/store.go
- x/reports/legacy/v2/store_test.go
This PR adds the `v4.0.0` upgrade handler and fixes any issue within the migrations scripts. 
---
I have...
I have...
> feat: add v4.0.0 upgrade handler

- app/upgrades/v400/upgrade.go
This PR fixed the v4.0.0 upgrade store loader to make sure there are no problems with the renamed posts store key.
---
I have...
I have...
> chore: fix v4.0.0 upgrade store loader

- cosmwasm/msg_parser.go
- cosmwasm/query_parser.go
Closes: #XXXX
Due to the wasm size issue after updating to `cosmwasm-std v1.0.0`, the custom serde tag is removed from desmos binding. This PR updates the wasm parser to the new json message. 
---
I have...
I have...
> feat: update wasm parser for v1.0.0 cosmwasm std

- x/profiles/spec/04-messages.md
- x/reactions/spec/04-messages.md
- x/reactions/spec/06-permissions.md
- x/relationships/spec/04-messages.md
- x/reports/spec/04-messages.md
- x/reports/spec/06-permissions.md
- x/subspaces/spec/04-messages.md
- x/subspaces/spec/06-permissions.md
- Fixed messages Proto links to match `v4.1.0`
- Fixed errors in permissions files
---
I have...
I have...
> docs: fixed specs problems

- .changeset/entries/03035f411831a66120ac594cc09a140201357bb0f763287b8f49acda6efbed13.yaml
- .changeset/entries/62bf6c9bac7b77295632276f7e66130725d7fec458bd73f5f195daea2905009f.yaml
- .changeset/entries/778ed3c87c8ba17a37bb9117fc0aa014f056400bb6fa661109af351e6cff1965.yaml
- .changeset/entries/7d2f19ca69bf6b743fe24a744181d1afee8015075d801dcaea4c9783ed128cca.yaml
- .changeset/entries/88359bd8fafae0d65d536627bc73880d65a9cad24048ca60a6c2420c028180f3.yaml
- .changeset/entries/e8fdc65b9f41e85409395d7e7b317f59f6d7be1ff3f8a92ebb30dafeb3254d4e.yaml
- .github/workflows/on-chain-upgrade.yml
- CHANGELOG.md
- app/app.go
- app/upgrades/v420/upgrade.go
- contrib/images/desmos-cosmovisor/Dockerfile
- contrib/images/desmos-cosmovisor/wrapper.sh
- contrib/upgrade_testnet/docker-compose.yml
- contrib/upgrade_testnet/submit_upgrade_proposal.sh
This PR includes all the last changes to be done before releasing `v4.2.0` of Desmos.
---
I have...
I have...
> chore: release v4.2.0

- contrib/upgrade_testnet/setup_genesis.py
Closes: #XXXX
This PR fixes release v4.4.1.
---
I have...
I have...
> fix: fix on-chain upgrade test

- .changeset/entries/a09a6ffccef899fabd051d4fb85a8fe057bd470686a9da040ffc9d11e72997c0.yaml
- .changeset/entries/b861c5fc81782dbccd7f5db530a207a324bfb4a4b81c3486100481cc90939e93.yaml
- .github/workflows/on-chain-upgrade.yml
- CHANGELOG.md
- app/app.go
- app/upgrades/v460/upgrade.go
This PR prepares the code for the next `v4.6.0` release of Desmos
---
I have...
I have...
> chore: release v4.6.0

- .changeset/entries/d53e0f53f940f8d05d053e2b774a226e9f7f912e4118cbb50e9d1b22b4f641c6.yaml
- x/reactions/keeper/genesis.go
- x/reactions/types/genesis.go
This PR fixes minor bugs within the `export` command. Particularly, it fixes some errors that might have been thrown if `initialRegisteredReactionID` or `initialReactionID` were not set, by forcing those values to be `1` as per default behavior
---
I have...
I have...
> fix: fix genesis export commands

- x/subspaces/spec/04-messages.md
Closes: #XXXX
This PR fixes the proto visualization of the subspaces messages visible at the [subspaces module](https://docs.desmos.network/developers/modules/subspaces/messages) docs page.
---
I have...
I have...
> docs: fix subspaces messgaes proto visualization

- docs/architecture/adr-017-subspace-fee-grant.md
- docs/architecture/adr-018-improve-subspace-treasury-account.md
This PR introduces a new structure of the subspace treasury account.
Closes: #XXXX
---
I have...
I have...
> docs(adr): New subspace treasury account structure

- x/profiles/abci.go
- x/profiles/keeper/alias_functions.go
- x/profiles/keeper/alias_functions_test.go
- x/profiles/keeper/invariants.go
- x/profiles/keeper/keeper_app_links.go
- x/profiles/keeper/keeper_chain_links.go
- x/profiles/keeper/keeper_chain_links_test.go
- x/profiles/keeper/keeper_dtag_transfers.go
- x/profiles/keeper/keeper_dtag_transfers_test.go
Closes: #XXXX
This PR removes the index parameter of iteration methods inside `x/profiles`. The index parameters are not used in current codebase, I believe it was used before applying`query.Paginate`.
---
I have...
I have...
> feat: improve profiles iteration methods

- .github/workflows/build-docs-preview.yaml
This PR fixes the setup of the `thollander/actions-comment-pull-request` action to use the proper variables so that the action does not add multiple comments on one PR but instead always edits the first that it creates.
---
I have...
I have...
> build(ci): fix build-docs-preview URL commenting

- docs/docs/02-developers/01-overview.md
- docs/docs/02-developers/03-tools-to-build.md
- docs/docs/02-developers/04-query-data.md
- docs/docs/02-developers/07-faq.md
> docs: fix typos

- docs/architecture/adr-017-subspace-fee-grant.md
This PR revises ADR-017 to adapt to the new treasury structure implementation.
---
I have...
I have...
> docs(adr): revise ADR 017 subspace fee grant

- go.mod
- go.sum
Closes: #1100 
---
I have...
I have...
> docs: update genesis file hashsum

- x/subspaces/keeper/alias_functions.go
Closes: #XXXX
Forwarding: https://github.com/desmos-labs/desmos/pull/1097#discussion_r1151683163
This PR intends to fix the subspace creation. `NewBaseAccount` does not generate account number and sequence, which will occur simulation test error after bumping to cosmos v0.47.0.
---
I have...
I have...
> fix: fix subspace account creation

- Makefile
Closes: #XXXX
This PR fixes the make file custom genesis sim test config path.
---
I have...
I have...
> chore: fix custom genesis sim test config path

- docs/architecture/adr-020-post-ownership-change.md
Closes: #XXXX
This PR revises the ADR 20: Post ownership transfer, which tend to make users prevent from being transferred reputation damaged posts.
---
I have...
I have...
> docs(adr): revise ADR-20: Post ownership transfer

- docs/architecture/adr-015-improve-chain-link-signature-support.md
- docs/architecture/adr-017-subspace-fee-grant.md
- docs/architecture/adr-018-improve-subspace-treasury-account.md
- docs/architecture/adr-019-post-moving.md
- docs/architecture/adr-019-subspace-post-moving.md
This PR represents the ADR of a new feature which will allow users to move their own posts between subspaces.
[DCD-323](https://forbole.atlassian.net/browse/DCD-323)
---
I have...
I have...
[DCD-323]: https://forbole.atlassian.net/browse/DCD-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs(adr): ADR-19: Subspace post migration

- x/reactions/simulation/operations.go
- x/reactions/simulation/operations_reactions.go
This PR fixes the sim tests of `x/reactions MsgRemoveReaction` by making sure the user removing the reaction is the of the reaction, instead of a generic user having the _react_ permission inside the subspace
---
I have...
I have...
> chore: fix reactions sim tests

- x/posts/types/codec.go
- x/profiles/types/codec.go
- x/reports/types/codec.go
Closes: #XXXX
This PR adds missing gov codec to desmos modules
---
I have...
I have...
> fix: add missing gov codec

- CHANGELOG.md
- x/posts/client/utils/cli.pb.go
- x/posts/spec/05-events.md
- x/posts/spec/08-client.md
- x/subspaces/client/cli/cli_feegrant_test.go
This PR updates the `posts` related type URLs inside the various documentation files.
---
I have...
I have...
> docs: update posts type URLs

- api/desmos/posts/module/v1/module.pulsar.go
- api/desmos/profiles/module/v1/module.pulsar.go
- api/desmos/reactions/module/v1/module.pulsar.go
- api/desmos/relationships/module/v1/module.pulsar.go
- api/desmos/reports/module/v1/module.pulsar.go
- api/desmos/subspaces/module/v1/module.pulsar.go
- api/desmos/supply/module/v1/module.pulsar.go
- app/app.go
- app/app_config.go
- app/desmos/cmd/chainlink/create_json.go
- app/desmos/cmd/chainlink/create_json_suite_test.go
- app/desmos/cmd/root.go
- app/encoding.go
- app/params/encoding.go
- go.mod
- go.sum
- testutil/network.go
- x/profiles/client/cli/cli_test.go
- x/profiles/client/utils/utils_test.go
- x/profiles/types/account_test.go
- x/relationships/types/expected_keepers.go
This PR updates the type returned from the `EncodingConfig` to be `simappparams.EncodingConfig`. This is to make sure that the `MakeEncodingConfig` method can be used whenever the `simappparams.EncodingConfig` type is used, such as in other tools like DJuno.
---
I have...
I have...
> refactor: update EncodingConfig return type

- x/profiles/spec/05-events.md
- x/profiles/spec/07-client.md
Closes: #XXXX
This PR updates the docs to fix profiles v2 into v3 since the current mainnet version is using profiles v3.
---
I have...
I have...
> docs: update profiles v2 into v3

- scripts/mutation-test.sh
Closes: #1159
This PR fixes the mutation test ci by removing tty from the script since github action does not support it.
See the error:
https://github.com/desmos-labs/desmos/actions/runs/5080361423/jobs/9127223711#step:4:11
---
I have...
I have...
> build(ci): remove tty from mutation test script

- app/app.go
- app/app_v2.go
- app/sim_test.go
- go.mod
- go.sum
Closes: #XXXX
This PR bumps wasmd to v0.40.0, which is released last week:
https://github.com/CosmWasm/wasmd/releases/tag/v0.40.0
---
I have...
I have...
> build(deps): bump wasmd to v0.40.0

- app/app_config.go
Closes: #XXXX
This PR adds the missing solomachine module registration for Desmos. 
Reference:
https://ibc.cosmos.network/v7.0.0/migrations/v6-to-v7.html#solo-machine-registration
Note: all the connections on Desmos are `07-tendermint` currently.
---
I have...
I have...
> fix: add missing solomachine registration

- x/subspaces/simulation/operations_sections.go
Closes: #XXXX
This PR fixes the move section simulation test that causes the invalid section path.
---
I have...
I have...
> fix(tests): fix move section simulation test

- .changeset/entries/6ed6afb12e9010ecd5e6f1d17080766a328d95d4ca1ff9008b55bcfc0afd20cc.yaml
- go.mod
- go.sum
This PR updated `ibc-go` to `v7.2.0` in order to solve a bug that broke all IBC-related transaction Ledger signing.
---
I have...
I have...
> build(deps)!: bump github.com/cosmos/ibc-go to v7.2.0

- .github/workflows/lint.yml
This PR fixes `git_diff` input by updating it into `PATTERNS`, since `SUFFIX_FILTER` was deprecated. See:
https://github.com/desmos-labs/desmos/actions/runs/5357566056/jobs/9718597745#step:4:1
---
I have...
I have...
> build(ci): fix git_diff input inside lint ci

- .github/workflows/docs.yml
Closes: #XXXX
This PR fixes the proto-swagger-gen by running it in sudo mode.
---
I have...
I have...
> build(ci): fix proto swagger gen

- docs/docs/02-developers/01-overview.md
- docs/docs/02-developers/03-tools-to-build.md
- docs/docs/02-developers/04-query-data.md
- proto/desmos/subspaces/v3/models.proto
- x/posts/spec/01-overview.md
- x/posts/spec/02-concepts.md
- x/posts/spec/03-state.md
- x/posts/spec/04-messages.md
- x/posts/spec/05-events.md
- x/posts/spec/08-client.md
- x/profiles/spec/07-client.md
- x/subspaces/spec/01-overview.md
- x/subspaces/spec/02-concepts.md
- x/subspaces/spec/03-state.md
- x/subspaces/spec/04-messages.md
- x/subspaces/spec/05-events.md
- x/subspaces/spec/06-permissions.md
- x/subspaces/spec/07-client.md
- x/supply/spec/03-client.md
- x/tokenfactory/spec/01-overview.md
- x/tokenfactory/spec/02-concepts.md
- x/tokenfactory/spec/03-state.md
- x/tokenfactory/spec/04-messages.md
- x/tokenfactory/spec/05-events.md
- x/tokenfactory/spec/06-params.md
- x/tokenfactory/spec/07-permissions.md
- x/tokenfactory/spec/08-client.md
This PR updates all the files inside various `spec` folders in order to match the changes made to various modules.
Depends-On: #1194 
---
I have...
I have...
> docs: update spec files to match latest changes

- x/profiles/spec/02-concepts.md
Fixing an error in the concepts documentation of the profile module.
---
I have...
I have...
> docs: fix profile concepts

- contrib/images/desmos-builder/Dockerfile
This PR updates wasmvm of desmos-builder into proper version.
---
I have...
I have...
> chore: update wasmvm of desmos-builder into 1.3.0

- app/upgrades.go
- app/upgrades/v6/upgrade.go
Closes: #XXXX
---
I have...
I have...
> fix: add missing IBC upgrade handler

- .changeset/config.yaml
- .changeset/entries/110685c056cf123bfab42140330553503f10e3ec69b13d2a6edb7c57c99a13d7.yaml
- .changeset/entries/12ef3d8c6142491afa3d1adac5b5e38ef63597e5dc766ae5b154b060ac81db27.yaml
- .changeset/entries/1ba1098efff36d4c20889fce9d089367d1343aa901848fc8267d89080328417a.yaml
- .changeset/entries/2233aa83f4ea3b3eb6a46cb4c45811a1ba167ce0a4da4face2a70ec94dbf6d87.yaml
- .changeset/entries/3df5614ff9581d5b7cbc540d8b53ff24cbdcc62d6891348fe0d7334cb8a17940.yaml
- .changeset/entries/6ed6afb12e9010ecd5e6f1d17080766a328d95d4ca1ff9008b55bcfc0afd20cc.yaml
- .changeset/entries/8acc72950132eb9a991b3df2c32b1ff3224aeae2cb5a7cd7884c850bea62f133.yaml
- .changeset/entries/99422ab5d7ce0d3b0e7d8e78079039e4bce487082a84ec0e3ef43d81495dd44c.yaml
- .changeset/entries/a0a7a23ce551e2e56ba482291f33844b90b593cfbd83da2f7c31796c04eb49ea.yaml
- .changeset/entries/e84e9f85faf0a0e85531a932ca56c8c5a45264cb97c0ee4c7127d52607b1d7ee.yaml
- CHANGELOG.md
This PR prepares the CHANGELOG and other files to release version `v6.0.0`.
---
I have...
I have...
> chore: release v6.0.0

- .changeset/entries/1183e24574a7230ac0c8500899bd6a3d4d1f9355874f543661587867e2944543.yaml
- app/desmos/cmd/root.go
Closes: #XXXX
This PR adds `pruning` and `snapshots` commands for Desmos.
---
I have...
I have...
> feat: add pruning and snapshot commands

- .changeset/entries/1183e24574a7230ac0c8500899bd6a3d4d1f9355874f543661587867e2944543.yaml
- .changeset/entries/43992e9f7a2a6ed33633e7cda8d69e2c0fb029abb0f90d99203f0718ae6ed613.yaml
- .changeset/entries/d0890a71e9f298d30c1bf12eeb4dc623cbfab8468236bbea10e9361c2df8789e.yaml
- .changeset/entries/e81ae400223608ff17c3f0dc3618d1c14274d283ecc3898ec0a9a46ad2912915.yaml
- CHANGELOG.md
This PR upates the CHANGELOG and changeset entries to get ready for Desmos Core `v.6.1.0` release.
---
I have...
I have...
> chore: release v6.1.0

- .changeset/entries/6903edfe80282ff8891b1e6838697af52e3a4b03293f4c1890bc602dc7fad90f.yaml
- app/wasm_config.go
Closes: #XXXX
This PR fixes the registration of the `QueryIncomingPostOwnerTransferRequests`.
---
I have...
I have...
> fix: fix incoming post owner transfer requests wasm config

- docs/src/css/custom.css
- docs/src/theme/SearchBar/styles.css
Fixed the search-bar width stuck to desktop mode in the mobile version of the docs
---
I have...
I have...
> docs: fixed search-bar width in mobile version

- .changeset/entries/a5d4d8510e8e501b9591599825f4359c58beafd9e78997cba09b2773d8aca3b2.yaml
- contrib/images/desmos-builder/Dockerfile
- go.mod
- go.sum
Closes: #XXXX
This PR bumps github.com/CosmWasm/wasmd to 0.44.0.
---
I have...
I have...
> build(deps): bump github.com/CosmWasm/wasmd to 0.44.0

- .github/labeler.yml
- .github/workflows/labeler.yml
This PR fixed the Labeler config to be compatible with the new action version
---
I have...
I have...
> build(ci): fix labeler config

- .changeset/entries/5e3de82a61f2f937aff9f8087f2bec00848fe16a18b4df0b32daa4b367a0b47e.yaml
- go.mod
- go.sum
This PR bumps `github.com/CosmWasm/wasmd` to `v0.45.0`.
---
I have...
I have...
> build(deps): bump github.com/CosmWasm/wasmd to v0.45.0

- CHANGELOG.md
- app/upgrades.go
- app/upgrades/v640/upgrade.go
This PR prepares the codebase for the next `v6.4.0` release. 
---
I have...
I have...
> chore: release v6.4.0

- go.mod
- go.sum
Closes: #XXXX
---
I have...
I have...
> build(deps): bump github.com/cosmos/cosmos-sdk to v0.47.8

- .github/ISSUE_TEMPLATE/bug_report.md
- STABLE_RELEASES.md
Closes: #XXXX
This PR updates the docs to update managers to core devs team.
---
I have...
I have...
> docs: update managers in docs
