go.mod
go.sum
x/magpie/alias.go
x/magpie/genesis.go
x/magpie/internal/keeper/handler.go
x/magpie/internal/keeper/keeper.go
x/magpie/internal/keeper/keeper_test.go
x/magpie/internal/keeper/querier.go
x/magpie/internal/keeper/querier_test.go
x/magpie/internal/types/msgs.go
x/magpie/internal/types/msgs_test.go
x/magpie/internal/types/session.go
x/magpie/internal/types/session_test.go
x/posts/alias.go
x/posts/client/cli/tx.go
x/posts/client/rest/rest.go
x/posts/genesis.go
x/posts/internal/keeper/common_test.go
x/posts/internal/keeper/handler.go
x/posts/internal/keeper/handler_test.go
x/posts/internal/keeper/keeper.go
x/posts/internal/keeper/keeper_test.go
x/posts/internal/keeper/querier.go
x/posts/internal/types/events.go
x/posts/internal/types/keys.go
x/posts/internal/types/like.go
x/posts/internal/types/like_test.go
x/posts/internal/types/msgs.go
x/posts/internal/types/msgs_test.go
x/posts/internal/types/post.go

This PR implements various `Post` and `Like` structure improvements. 
Also, the various messages have been revisited in order to delete useless time fields. 
Tests have been added and documentation has been written.
Closes #39

Post and Like structure revist

---

Makefile
Makefile.ledger
contrib/devtools/Makefile
contrib/devtools/install-golangci-lint.sh
x/magpie/internal/keeper/keeper_test.go
x/magpie/internal/types/msgs.go
x/magpie/internal/types/session_test.go
x/posts/internal/keeper/keeper.go
x/posts/internal/keeper/keeper_test.go
x/posts/internal/types/post.go

Improved how `Makefile` is written, including the `contrib/devtools` Makefile which allows for easy `golangci-lint` tools to be downloaded and installed.

Makefile improvements

---

.golangci.yml
cmd/desmosd/main.go
cmd/desmosd/testnet.go
go.mod
go.sum
x/posts/alias.go
x/posts/client/cli/tx.go
x/posts/client/rest/rest.go
x/posts/genesis.go
x/posts/internal/keeper/common_test.go
x/posts/internal/keeper/handler.go
x/posts/internal/keeper/handler_test.go
x/posts/internal/keeper/keeper.go
x/posts/internal/keeper/keeper_test.go
x/posts/internal/keeper/post_response.go
x/posts/internal/keeper/post_response_test.go
x/posts/internal/keeper/querier.go
x/posts/internal/types/keys.go
x/posts/internal/types/like.go
x/posts/internal/types/msgs.go
x/posts/internal/types/msgs_test.go
x/posts/internal/types/post.go
x/posts/internal/types/post_test.go

This PR implements the support for discussion as discussed into the proper issue.  
Closes #13
**Note**. Please merge this after #42 and #44 have been merged.

Discussion implementation

---

x/magpie/internal/keeper/handler.go
x/magpie/internal/keeper/handler_test.go
x/posts/client/cli/tx.go
x/posts/client/rest/rest.go
x/posts/internal/keeper/handler.go
x/posts/internal/keeper/handler_test.go
x/posts/internal/keeper/keeper.go
x/posts/internal/keeper/keeper_test.go
x/posts/internal/keeper/post_response_test.go
x/posts/internal/types/events.go
x/posts/internal/types/like.go
x/posts/internal/types/like_test.go
x/posts/internal/types/post.go
x/posts/internal/types/post_test.go

Added the handling for the already existing `MsgUnlikePost` as well as the CLI/REST transaction creation.  
Also, removed the emission of duplicated events and improved how events are returned from the handlers inside the `sdk.Result` type (this change avoid duplicated events to be returned).

Unlike handling addition and events improvements

---

CHANGELOG.md
x/posts/internal/types/keys.go
x/posts/internal/types/msgs.go
x/posts/internal/types/msgs_test.go
x/posts/internal/types/post.go
x/posts/internal/types/post_test.go

This PR allows to cap the post message length to 500 characters, fixing #67

Implemented the post message cap to 500 characters

---

CHANGELOG.md
cli_test/cli_posts_test.go
cli_test/test_helpers.go
x/posts/client/cli/tx.go
x/posts/internal/types/msgs_test.go
x/posts/internal/types/post_media_test.go

Updating the CLI create post's command to better fit the latest edits. Now the message field is optional and the allow-comments one become a flag.
Closes #117

Update the post creation CLI command

---

CHANGELOG.md
docs/types/reaction.md
x/posts/client/cli/tx.go
x/posts/internal/types/msgs.go
x/posts/internal/types/msgs_test.go

This PR allows the creation of posts with empty message if a poll inside them is specified.
Closes #148.

Allow empty messages with non-empty polls

---

x/magpie/alias.go
x/posts/alias.go
x/posts/client/cli/tx.go
x/posts/internal/types/alias.go
x/posts/internal/types/models/alias.go
x/profile/alias.go

This PR fixes the typo inside the cli command `posts create`.
Closes #156.

Fixed typo in cli command tx posts create

---

cli_test/cli_profile_test.go
cli_test/test_helpers.go
x/magpie/alias.go
x/posts/alias.go
x/posts/internal/types/alias.go
x/posts/internal/types/models/alias.go
x/profile/alias.go
x/profile/client/cli/tx.go

This PR fixes the bug inside the `profile delete` cli cmd.
Closes #166.

Profile CLI delete cmd fix

---

CHANGELOG.md
cli_test/cli_profile_test.go
cli_test/test_helpers.go
x/profiles/client/cli/keys.go
x/profiles/client/cli/tx.go

Changes:
- Fixed the `tx profiles save --help` description (fixes #206) 
- Changed the `tx profiles save` flags names (fixes #207)
- Fixed the `tx profiles save` form moving the DTag to the arguments (fixes #208)

Profiles save command fixes

---

cli_test/test_helpers.go
x/profiles/client/cli/tx.go

This PR fixes the problem raised inside issue [281](https://github.com/desmos-labs/desmos/issues/281).
Closes #281 .

Fixed dTag CLI command

---

CHANGELOG.md
x/relationships/types/events.go

This PR removes the `relationship` event key prefix.
Closes #300.

Remove relationship event key prefix

---

CHANGELOG.md
cli_test/cli_profile_test.go
x/profiles/keeper/handler.go
x/profiles/keeper/handler_test.go
x/relationships/types/events.go

This PR fixes the possibility to request a transfer of an empty dTag.
This situation occurs when the dTag owner doesn't have a profile.
Closes #293 .

Empty dTag transfer fix

---

.github/workflows/release.yml
CHANGELOG.md
Makefile
go.mod
go.sum

Changes:
- Updated Cosmos to v0.42.0 (closes #378)
- Added release workflow to release compiled binaries when a tag is created
- Changed the old Changelog entries to use `\#` instead of `#` when referencing an issue number

Version v0.15.4

---

app/app.go
app/sim_test.go

- Integrate ibc transfer module
- closes #382

Integrate ibctransfer

---

x/profiles/simulation/genesis.go

This PR fixes the bugs that were present inside the simulation tests for the `x/profiles` module.  
Now, when creating genesis relationships, we check for double ones and avoid inserting them. This allows to avoid having the chain explode at genesis.

Simulation tests fixes

---

CHANGELOG.md
proto/desmos/profiles/v1beta1/genesis.proto
proto/desmos/profiles/v1beta1/models.proto
x/profiles/types/account.go
x/profiles/types/account_test.go

This PR updated how a profile is updated, fixes #416

Profile serialization fix

---

.github/workflows/docs.yml
Makefile
client/docs/config.json
client/docs/swagger-ui/swagger.yaml
scripts/protoc-swagger-gen.sh

This PR is the implementation of #438, it includes:
* Fix `proto-swagger-gen` script
* Implement `proto-swagger-gen` function in Makefile
* Set proto targets to `client/docs/config.json`
* Generate `client/docs/swagger-ui/swagger.yaml` by `proto-swagger-gen`
Closes #438

Implement swagger documentation generation

---

app/app.go
contrib/images/desmos-env/Dockerfile

This PR tries to fix the liveliness test

Fix liveliness test

---

app/desmos/cmd/root.go
app/desmos/cmd/sign.go
app/desmos/cmd/sign_test.go

This PR adds the `sign` command to the `desmos` root command, allowing to sign any data. No changelog entry is required since this is part of the things that are needed in order to implement applications links

Add sign command

---

testutil/profiles.go
x/profiles/keeper/alias_functions_test.go
x/profiles/keeper/common_test.go
x/profiles/keeper/genesis_test.go
x/profiles/keeper/grpc_query_test.go
x/profiles/keeper/invariants_test.go
x/profiles/keeper/keeper_app_links_test.go
x/profiles/keeper/keeper_blocks_test.go
x/profiles/keeper/keeper_chain_links_test.go
x/profiles/keeper/keeper_dtag_transfers.go
x/profiles/keeper/keeper_dtag_transfers_test.go
x/profiles/keeper/keeper_params_test.go
x/profiles/keeper/keeper_relationships_test.go
x/profiles/keeper/keeper_test.go
x/profiles/keeper/msg_server_blocks_test.go
x/profiles/keeper/msg_server_chain_link_test.go
x/profiles/keeper/msg_server_dtag_transfers_test.go
x/profiles/keeper/msg_server_relationships_test.go
x/profiles/keeper/msgs_server_profile_test.go
x/profiles/keeper/relay_app_links_test.go
x/profiles/keeper/relay_chain_links.go
x/profiles/keeper/relay_chain_links_test.go
x/profiles/types/account_test.go
x/profiles/types/models_app_links_test.go
x/profiles/types/models_params_test.go

This PR improves the keeper tests for the `x/profiles` module. References #481

Profiles keeper tests improvements

---

CHANGELOG.md
x/profiles/keeper/grpc_query.go
x/staging/posts/keeper/grpc_query.go
x/staging/subspaces/keeper/grpc_query.go

This PR is the implementation of #535.
Closes #535

Improve pagination

---

go.mod
go.sum

This PR updates the Cosmos SDK to `v0.42.7`. Closes #550

Update Cosmos to v0.42.7

---

.changeset/entries/b61d05b629d30f51f93c5e6efce23ff77d91f1f8fba588aa85d40d67d16f92e7.yaml
x/profiles/client/cli/cli_profile.go

add: flag indicator in example

---

.changeset/entries/7b2791e321645b1b6ce07eb919f8aa1680a304e4c14b74d95994a5b6d88fef5d.yaml
.github/workflows/on-chain-upgrade.yml
CHANGELOG.md
app/app.go

This PR prepares the release for the `v2.3.0-testnet` version of Desmos, which fixes how the application link verification flow is handled in order to avoid any error due to parallel verification requests or deleted links. 
---
I have...
I have...

chore: release v2.3.0-testnet

---

.changeset/entries/fc6dda08613b49d8b7c870c929fc0f026474816d08093146bc8ac6ddf6257f45.yaml
x/profiles/types/codec.go
x/profiles/types/msgs_chain_links_test.go

This PR fixes a bug that currently makes it impossible to properly serialize an `AddressData` value using Amino. 
Currently the `AddressData` interface has two implementations that are serialized as follows when using Amino: 
- `Base32Address`
```json
{
"prefix": "",
"value": ""
}
```
- `Bech58Address`
```json
{
"value": ""
}
```
However, since it is an interface, it should have been registered properly and should be serialized as follow: 
- `Base32Address`
```json
{
"type": "desmos/Bech32Address",
"value": {
"prefix": "",
"value": ""
}
}
```
- `Base58Address`
```json
{
"type": "desmos/Base58Address",
"value": {
"value": ""
}
}
```
---
I have...
*All …

fix: allow AddressData to be properly serialized using Amino

---

app/app.go
app/export.go
x/profiles/module.go
x/profiles/types/models_params.go

This PR exposes all the keepers inside the `DesmosApp` so that they can be used externally (such as from BDJuno). It also fixes small lint issues that I've found
---
I have...
I have...

chore: expose keepers

---

.github/workflows/test.yml
x/profiles/module.go

Starting with Desmos `v2`, due to the `go.mod` module change (from `github.com/desmos-labs/desmos` to `github.com/desmos-labs/desmos/v2`) the entire coverage has drastically decreased. This was due to the fact that Codecov couldn't find anymore the module `github.com/desmos-labs/desmos` and all the files in the new module were not tracked. 
To fix this, I have now revisited the Github workflow that computes the coverage, by editing how the final `coverage.txt` is generated. From now, even if we change the module name inside the `go.mod` file we should see the coverage always correct.
**NOTE**: The `.go` file change is only there to trigger the CI that computes the coverage and to see whether it's fixed or not 
---
*All items are required. Please add a note to the item if the item is not …

ci: fixing coverage

---

x/subspaces/keeper/msg_server.go
x/subspaces/keeper/msg_server_test.go

Closes: #746 
This PR fixes the parameter order bug of the subspace creation in the msg server.
---
I have...
I have...

fix: wrong message values usage during subspace creation

---

x/subspaces/client/cli/cli_test.go

Closes: #XXXX
I don't know if it's intentional or not, but the `QueryUserPermissions` is returning also the group 0 permissions.
This because of the combination of inherited permissions. If this is intentional, than this PR fixes the failing CLI tests that were not considering that permissions in the results.
---
I have...
I have...

fix: Fixed user query permissions CLI test

---

.changeset/entries/6e78e6f7f9486799935df288f3d1467a646116fddc2952e79e559b1d4cc58d79.yaml
testutil/context.go
x/profiles/legacy/v5/store_test.go
x/subspaces/keeper/migrations.go
x/subspaces/keeper/msg_server.go
x/subspaces/keeper/msg_server_test.go
x/subspaces/legacy/v2/store.go
x/subspaces/legacy/v2/store_test.go
x/subspaces/module.go
x/subspaces/types/permissions.go
x/subspaces/types/permissions_test.go

This PR adds permissions sanitation before storing the permissions while handling a `MsgSetUserGroupPermissions` or `MsgSetUserPermissions`. 
Special review required by @manu0466 since he was the one to report the bug (and suggest a solution). 
Closes: #800 
---
I have...
I have...

fix: sanitize permissions

---

.changeset/entries/32ba778bad884cf9429f4a0e2d8525170662fa1592a4b25daadc6c9ac4275e2b.yaml
x/subspaces/keeper/msg_server.go
x/subspaces/keeper/msg_server_test.go
x/subspaces/simulation/operations_groups.go
x/subspaces/simulation/operations_permissions.go
x/subspaces/types/msgs.go
x/subspaces/types/msgs_test.go

This PR changes how `MsgSetUserPermissions` is validated and how `MsgSetUserGroupPermissions` is handled to make sure a user cannot set their own permissions or the permissions of a group they are part of. 
---
I have...
I have...

fix: do not allow setting permissions for self

---

.changeset/entries/8fea7719728d408975e08ec2ca629f6241c68afe263cc5897d7ebcb0856b4520.yaml
x/profiles/client/cli/cli_chain_links.go
x/profiles/client/cli/cli_dtag_requests.go

This PR fixes some CLI commands args number to properly match the expected ones.
---
I have...
I have...

fix: fix CLI commands args number

---

x/fees/types/params.go
x/fees/types/params_test.go

This PR adds a check to make sure that there cannot be multiple min fees for the same message type inside the `x/fees` on-chain parameters.
---
I have...
I have...

fix: avoid multiple min fees for same message type

---

.changeset/entries/6f0a061bd4ae3038eb8a5a71d9a3b1e6b88397a4e785bda00fec5fbd8bd0737b.yaml
x/relationships/keeper/migrations.go
x/relationships/legacy/v1/keys.go
x/relationships/legacy/v2/store.go
x/relationships/legacy/v2/store_test.go
x/relationships/module.go

This PR updates the `x/relationships` store keys to use single bytes instead of string prefixes, to slim the storage space.
---
I have...
I have...

fix: simplify x/relationships store keys

---

.changeset/entries/68d07218bf30b0b984be4c29146eb71f915df11721ab81b8eec2595ab493ae4d.yaml
x/profiles/client/cli/cli_app_links.go
x/profiles/client/cli/cli_app_links_test.go
x/profiles/client/cli/cli_chain_links.go
x/profiles/client/cli/cli_chain_links_test.go
x/profiles/client/cli/query.go

This PR adds missing profiles commands, `GetQueryChainLinkOwners` and `GetQueryApplicationLinkOnwers`.
---
I have...
I have...

fix: add missing profiles commands

---

.changeset/entries/0b375405b7cd05aced303d5752096b2321d0e60a0559ec4c20e7f538debdb738.yaml
go.mod
go.sum

This PR updates the Cosmos SDK to the latest version
---
I have...
I have...

build(deps): bump github.com/desmos-labs/cosmos-sdk from 0.45.4 to 0.45.5

---

.changeset/entries/d4afbea9357029666b3c020a5fecbced824a4ceca62ae3c2d196c476e29d03a8.yaml
app/desmos/cmd/root.go

This PR fixes the initialization of the app when running the `export` command so that CosmWASM files can be read properly and its state can be exported correctly. Thanks to @webmaster128 for helping debugging this
---
I have...
I have...

fix: fix default node home when exporting the state

---

.changeset/entries/2ceedb22572eba8499b4b7abf8c4b38789a979fa8a852a3537dc9cba4b81bc16.yaml
x/subspaces/types/codec.go
x/subspaces/types/msgs_test.go

This PR adds Amino encoding supporrt for `x/subspaces` messages
---
I have...
I have...

fix!: add Amino support for x/subspaces messages

---

x/relationships/spec/01_concepts.md
x/relationships/spec/02_state.md
x/relationships/spec/03_messages.md
x/relationships/spec/04_events.md
x/relationships/spec/05_client.md
x/relationships/spec/README.md

This PR adds the spec folder inside the `x/relationships` module, containing the whole specification.
Depends-On: #829
Depends-On: #838
---
I have...
I have...

docs: add x/relationships spec

---

client/docs/config.json
client/docs/swagger-ui/swagger.yaml

This PR updates the Swagger config and UI to include `x/fees` and `x/supply` queries. 
---
I have...
I have...

docs: updated Swagger config and UI

---

x/profiles/types/genesis.go

This PR fixes the `x/profiles` genesis unmarshalling adding the missing `UnpackInterfaces` method for the `GenesisState` type
---
I have...
- x ] targeted the correct branch (see [PR Targeting](https://github.com/desmos-labs/desmos/blob/master/CONTRIBUTING.md#pr-targeting))
I have...

fix: fix x/profiles genesis unpacking

---

x/posts/keeper/external_hooks.go
x/posts/keeper/external_hooks_test.go
x/reports/keeper/external_hooks.go
x/reports/keeper/external_hooks_test.go

This PR fixes the `x/posts` and `x/reports` external hooks to not overwrite the data. 
---
I have...
I have...

fix: fix external hooks to not overwrite data

---

app/app.go
x/posts/abci_test.go
x/posts/keeper/alias_functions.go
x/posts/keeper/common_test.go
x/posts/keeper/keeper.go
x/posts/keeper/msg_server.go
x/posts/keeper/msg_server_test.go
x/posts/simulation/operations_polls.go
x/posts/simulation/operations_posts.go
x/posts/types/expected_keepers.go
x/reports/keeper/alias_functions.go
x/reports/keeper/common_test.go
x/reports/keeper/keeper.go
x/reports/keeper/msg_server.go
x/reports/keeper/msg_server_test.go
x/reports/simulation/operations_reports.go
x/reports/types/expected_keepers.go

This PR adds the requirement to have a profile when sending a `MsgCreatePost`, `MsgAnswerPoll` and `MsgCreateReport`. 
This is done due to the fact that those features should be used only by users of the protocol, and as a (very naive) spam prevention system. 
---
I have...
I have...

feat: require a profile for MsgCreatePost, MsgAnswerPoll and MsgCreateReport

---

go.mod
x/reports/client/cli/cli_test.go
x/reports/client/cli/flags.go
x/reports/client/cli/query.go
x/reports/client/cli/tx.go

This PR improves the CLI commands organization for the `x/reports` module. 
---
I have...
I have...

chore: improve the x/reports CLI commands

---

x/reports/keeper/reports.go
x/reports/keeper/reports_test.go

This PR improves the reports validation tests
---
I have...
I have...

chore: improve x/reports validation test

---

x/profiles/spec/02-concepts.md
x/profiles/spec/04-messages.md

Closes: #XXXX
---
I have...
I have...

docs: fixed profiles specs links

---

x/posts/client/cli/cli_test.go
x/posts/client/cli/query.go

This PR fixes a bug within the CLI command to query the poll answers.
Closes: #928
---
I have...
I have...

fix: fixed poll answers query CLI command

---

.changeset/entries/e2fa8c09bd5014df0ee3eadc345fd6d139a7196709dd70539791c2154a36a2af.yaml
x/reactions/keeper/msg_server.go
x/reactions/keeper/msg_server_test.go

This PR fixes the `x/reactions` events types and missing attributes.
---
I have...
I have...

chore: fix x/reactions events

---

.changeset/entries/746e35e47af0507db333384fe80011d6170bc2c7ffb4c742da6d9d8b2513f586.yaml
x/posts/types/models.go
x/posts/types/models_test.go

This PR removes the position validation from within a post's entities. This is done to make sure that DApps that store the post's text on other places (i.e. IPFS or any external storage) can use the tags properly. 
Before, it wasn't possible to use a tag specifying `start` and `end` values that where exceeding a post `text` length. But for posts that store their text on other storage solutions, it doesn't make sense to check for this. Instead, allowing to specify arbitrary values for `start` and `end` indexes allows to support these cases as well. 
---
I have... …

fix: remove position validation from post entities and references

---

x/posts/types/codec.go

This PR fixed the `AttachmentContent` interface registered version in the `x/posts` codec. 
---
I have...
I have...

fix: fixed x/posts codec interface registered version

---

x/reports/client/cli/query.go
x/reports/client/cli/tx.go

Closes: #XXXX
This PR fixes some example descriptions in tx commands and some query commands names that collides with others.
---
I have...
I have...

chore: fix wrong names inside reports CLI commands

---

.changeset/entries/a95f200d5bb4f0ae79b9f221e0ef22e7266af1b3064faeca87fcaa56168079f1.yaml
x/profiles/types/wasm.go
x/profiles/wasm/common_test.go
x/profiles/wasm/msg_parser.go
x/profiles/wasm/msg_parser_test.go

Closes: #XXXX
This PR added missing wasm `x/profiles` unlink msgs parser. 
---
I have...
I have...

fix: added missing unlink wasm msgs parser

---

x/reactions/client/cli/query.go
x/reactions/client/cli/tx.go

Closes: #XXXX
Minor fixes to CLI commands examples of `x/reactions` module.
---
I have...
I have...

chore: fix `x/reactions` CLI commands examples

---

x/reports/types/wasm.go

Fixed the json field naming of the struct `ReportsMsg` used to deserilize the messages received from cosmwasm.
---
I have...
I have...

fix: fix json fields naming of ReportsMsg

---

.changeset/entries/62bf6c9bac7b77295632276f7e66130725d7fec458bd73f5f195daea2905009f.yaml
x/posts/keeper/migrations.go
x/posts/keeper/msg_server.go
x/posts/keeper/msg_server_test.go
x/posts/legacy/v4/store.go
x/posts/legacy/v4/store_test.go
x/posts/module.go
x/posts/simulation/operations_polls.go
x/posts/spec/04-messages.md

This PR fixes a bug within the `x/posts` module that currently allows users to answer a poll even when it's already ended.
---
I have...
I have...

fix: do not allow to answer a poll after voting period ends

---

.github/workflows/benchmarks.yml
Makefile

This PR adds a new workflow to run benchmarks tests during each PR/commit to the master branch. 
Thanks to @bragaz for the original work done inside #723. 
---
I have...
I have...

build: add benchmarks workflow

---

.changeset/entries/e8fdc65b9f41e85409395d7e7b317f59f6d7be1ff3f8a92ebb30dafeb3254d4e.yaml
x/profiles/client/cli/cli_profile_test.go
x/profiles/keeper/grpc_query.go
x/profiles/keeper/grpc_query_test.go

Currently, querying a non-existing profile returns `nil` instead of error with `profile not found for address/dtag`.
This PR fixes the response of `Profile` behavior mentioned above. 
---
I have...
I have...

fix!: profile query returns nil if profile does not exist

---

.changeset/entries/bf68d0c892177d2c1249cdacc6e9f283c42413d91a6fa33be87a8288ae5d2b0f.yaml
x/profiles/keeper/migrations.go
x/profiles/legacy/v5/types/models_params.go
x/profiles/legacy/v7/store.go
x/profiles/legacy/v7/store_test.go
x/profiles/module.go

This PR adds the `x/profiles` params upgrade that was missing inside `v4.2.0` and is currently causing errors when trying to store a profile (see [here](https://morpheus.desmos.network/transactions/85A1E1BB984CB96BABBDEE27F3F50FF455182B70A65DD03E24C30B817817B68E)).
---
I have...
I have...

fix: add missing profiles params upgrade

---

.github/workflows/lint.yml
.golangci.yml

This PR updates the GitHub lint workflow to use `make lint` instead of `golangci-lint-action`. 
---
I have...
I have...

build(ci): fix lint workflow to use make lint

---

.changeset/entries/eeb37f006aa774085d2a9d2674c3b872ef5968924a3f33e763a89de026b1a88e.yaml
contrib/images/desmos-builder/Dockerfile

This PR bumps the `wasmvm` version to `v1.1.1` inside the builder Dockerfile
---
I have...
I have...

build: bump wasmvm to v1.1.1 inside builder Dockerfile

---

.changeset/entries/b1b51cba6203f38f3d8eaf287c8107352f484770bc5bc833789cf4965a3fa360.yaml
app/desmos/cmd/root.go

This PR adds some missing `BaseApp` options when initializing a new `DesmosApp` instance
---
I have...
I have...

feat: add missing BaseApp options

---

.changeset/entries/3683281eb33362e34b90fb34583413bdbc77a382d143ca61470e39138ca1784c.yaml
app/desmos/cmd/chainlink/builder/multi/builder.go
app/desmos/cmd/chainlink/create_json.go
app/desmos/cmd/sign/sign.go
app/export.go
x/posts/client/utils/utils.go
x/posts/simulation/operations.go
x/profiles/client/utils/utils.go
x/profiles/keeper/keeper.go
x/profiles/keeper/relay_app_links.go
x/profiles/keeper/relay_chain_links.go
x/profiles/legacy/v4/store.go
x/profiles/legacy/v5/types/models_chain_links.go
x/profiles/simulation/operations.go
x/profiles/simulation/utils.go
x/profiles/types/models_chain_links.go
x/profiles/types/models_packets.go
x/profiles/types/msgs_app_links.go
x/reactions/client/utils/utils.go
x/relationships/legacy/v1/store.go
x/relationships/simulation/operations.go

This PR adds the Ledger support inside the `sign` command by wrapping the value into a transaction memo before signing it. 
---
I have...
I have...

feat: support Ledger while signing values 

---

.changeset/entries/f7bb961b8872d11fc00ebe6d43c2e5a6fae4f1fb0e63eb9f8b2d3db360260b97.yaml
app/app.go
x/posts/testutil/expected_keepers_mocks.go
x/profiles/keeper/genesis_test.go
x/subspaces/client/cli/tx_treasury.go
x/subspaces/client/cli/tx_treasury_test.go
x/subspaces/keeper/msg_server_treasury.go
x/subspaces/legacy/v5/store.go
x/subspaces/legacy/v5/store_test.go
x/subspaces/types/models_test.go
x/subspaces/types/msgs_treasury_test.go

This PR adds the missing Wasm snapshotter extension inside the `app.go` file. This is an attempt to fix the bug that currently makes it impossible to properly use state sync due to CosmWasm contracts not being included inside the snapshots.
---
I have...
I have...

fix: register missing Wasm snapshotter extension

---

.changeset/entries/910f8ded0fd0361d9d354227986d2a425ee4ec342e8747345ea97261d383f4bf.yaml
x/subspaces/types/codec.go
x/subspaces/types/msgs_test.go

This PR adds the registration of the `MsgDeleteSubspace` within the module's Amino codec.
Once this is merged, this change should also be backported to `4.8.x` in order to release a new version that fixes this in both the testnet and the mainnet.
---
I have...
I have...

fix!: register MsgDeleteSubspace within Amino codec

---

.changeset/entries/1fa3878e93e29ad214d2472a469e39295f58c02107793d13d00d041c01dcaabb.yaml
app/app.go

This PR integrates ibc fee middleware for ibc modules, allowing the relayer operators to receive tokens when submit the ibc transactions.
This integration follows [this guide](https://ibc.cosmos.network/main/middleware/ics29-fee/integration.html).
Note:
The channel to support ibc fee middleware should have the version like:
```json
{"fee_version": "ics29-1", "app_version": "ics20-1"}
```
If the version does not include `fee_version`, for example `ics20-1`, then the channel will be considered without middleware, then passing the version onto underlying IBC module and also tagging the channel is not `FeeEnabled`. The channel version is set in relayer side. So it should work properly integrate ibc fee in our side app only. See [here](https://github.com/cosmos/ibc-go/blob/v4.3.0/modules/apps/2 …

feat: integrate ibc fee middleware

---

.changeset/entries/be9c9c9795f61af352d633a8b7d40882a765149a7c5ad7a7c5d666feb4809151.yaml
app/app.go

This PR integrates ICS27 interchain account module to Desmos, the integration follows [this guide](https://ibc.cosmos.network/main/apps/interchain-accounts/integration.html).
Depends-On: #1081
---
I have...
I have...

feat: integrate interchain account

---

docs/architecture/adr-020-post-ownership-change.md

This PR represents the ADR for a new feature that will allow users to transfer the ownership of their posts to another user.
---
I have...
I have...

docs(adr): ADR-20: Post ownership transfer

---

.changeset/entries/a9ab12fa36aa608799c52430213523aa1b37fddcf64f76204c344a61a25be86d.yaml
.github/workflows/sims.yml
Makefile
app/sim_test.go
contrib/images/desmos-builder/Dockerfile
contrib/images/desmos-cosmovisor/Dockerfile
go.mod
go.sum
x/posts/wasm/common_test.go
x/reactions/legacy/v2/store_test.go
x/reactions/wasm/common_test.go
x/reports/keeper/common_test.go
x/reports/wasm/common_test.go

This PR 
- bumps `github.com/cosmos/cosmos-sdk` to `v0.47.2`
- bumps `github.com/cometbft/cometbft` to `v0.37.1`
- bumps `github.com/cometbft/cometbft-db` to `v0.8.0`
Closes #1122 
Closes #1123
---
I have...
I have...

build(deps): bump cosmos-sdk, cometbft cometbft-db

---

app/app.go
x/fees/module.go

Closes: #XXXX
This PR fixes `x/fees` constructor, that adds a missing legacy subspace to the module.
---
I have...
I have...

fix: fix `x/fees` constructor

---

.changeset/entries/b7c4628489c4494a06a0614c1668e6a4e834584657695d2ab54ed3923b819b8e.yaml
app/app.go
contrib/images/desmos-builder/Dockerfile
go.mod
go.sum

This PR bumps `github.com/CosmWasm/wasmd` to `v0.40.0-rc.1`
---
I have...
I have...

build(deps): bump github.com/cosmwasm/wasmd to v0.40.0-rc.1

---

docs/architecture/adr-021-subspace-specific-custom-fee-tokens.md

Closes: #XXXX
This PR introduces the subspace specific custom fee tokens by the ADR.
---
I have...
I have...

docs(adr): ADR-21: Subspace specific custom fee tokens

---

.changeset/entries/3a100bf361284b082e267a3ae553e65c258a5c083b3d4a706137038eab1f1b51.yaml
x/reactions/simulation/operations_reactions.go
x/subspaces/keeper/migrations.go
x/subspaces/legacy/v6/store.go
x/subspaces/legacy/v6/store_test.go
x/subspaces/module.go
x/subspaces/simulation/operations_groups.go
x/subspaces/types/models.go
x/subspaces/types/msgs.go
x/subspaces/types/msgs_test.go

Closes: #XXXX
This PR fixes the bug that we allow to move the default group to other section, it causes `test-sim-import-export` error happens the following steps:
1. Create a new subspace and `SaveSubspace` creates a default user group as well
2. Create a new section with id `1`, then default group key become `subspace-1 section-1 group-0`
3. Move default group to new section `1`
4. Export genesis then import it, the new app state will differ with the original one since `SaveSubspace` creates default group again on the key `subspace-1 section-0 group-0`
As every one are the members inside default group, we should refuse to move group to other sections.
---
please add links to any relevant follow up …

fix: refuse to move default user group

---

app/desmos/cmd/sign/sign.go

This PR fixes the following error that existed when using the `desmos sign` command with a Ledger device after upgrading to Cosmos `v0.47.x`:
```
Error: got empty address in SIGN_MODE_LEGACY_AMINO_JSON handler: invalid request
```
---
I have...
I have...

fix: empty address error when using sign command

---

x/reports/keeper/common_test.go
x/reports/keeper/external_hooks.go
x/reports/keeper/external_hooks_test.go
x/reports/keeper/genesis_test.go
x/reports/keeper/invariants_test.go
x/reports/keeper/msg_server_test.go
x/reports/keeper/reports_test.go
x/reports/testutil/expected_keepers_mocks.go

This PR improves the x/reports tests using gomock.
---
I have...
I have...

refactor(tests): improve x/reports tests using gomock

---

x/posts/types/codec.go
x/posts/types/msgs_owner_transfer_test.go
x/profiles/types/codec.go
x/reactions/types/codec.go
x/relationships/types/codec.go
x/reports/types/codec.go
x/subspaces/types/codec.go

This PR replaces legacy amino registration of msgs into `RegisterAminoMsg` in order to avoid the bug that a registered Msg name that is too long when signing on ledger Nano device. See:
https://github.com/cosmos/cosmos-sdk/issues/10870
---
I have...
I have...

refactor: use `RegisterAminoMsg` to register Amino encodings

---

docs/docs/05-testnet/04-join-public/04-state-sync.md

Closes: #XXXX
This PR fix the testnet statsync docs.
---
I have...
I have...

docs: fix test statesync docs

---

.changeset/entries/110685c056cf123bfab42140330553503f10e3ec69b13d2a6edb7c57c99a13d7.yaml
x/subspaces/abci.go
x/subspaces/abci_test.go
x/subspaces/keeper/alias_functions.go
x/subspaces/keeper/common_test.go
x/subspaces/keeper/feegrant.go
x/subspaces/keeper/feegrant_test.go
x/subspaces/keeper/genesis_test.go
x/subspaces/keeper/migrations.go
x/subspaces/legacy/v7/store.go
x/subspaces/legacy/v7/store_test.go
x/subspaces/module.go
x/subspaces/simulation/decoder.go
x/subspaces/simulation/decoder_test.go
x/subspaces/types/keys.go
x/subspaces/types/keys_test.go
x/subspaces/types/models_feegrant.go
x/subspaces/types/models_feegrant_test.go

This PR implements expired subspace fee grant deletion mentioned in [ADR-017](https://github.com/desmos-labs/desmos/blob/master/docs/architecture/adr-017-subspace-fee-grant.md#store-1).
---
I have...
I have...

feat!: implement expired subspace fee grant deletion

---

.changeset/entries/3df5614ff9581d5b7cbc540d8b53ff24cbdcc62d6891348fe0d7334cb8a17940.yaml
app/app.go
app/app_config.go
app/app_test.go
app/desmos/cmd/root.go
app/sim_test.go
app/wasm_config.go
cosmwasm/msg_parser.go
cosmwasm/query_parser.go
go.mod
go.sum
testutil/ibctesting/helper.go
testutil/network.go
x/posts/wasm/msg_parser.go
x/profiles/wasm/msg_parser.go
x/reactions/wasm/msg_parser.go
x/relationships/wasm/msg_parser.go
x/reports/wasm/msg_parser.go
x/subspaces/wasm/msg_parser.go

This PR bumps wasmd to 0.41.0.
---
I have...
I have...

build(deps)!: bump wasmd to 0.41.0 from 0.40.0

---

app/upgrades.go
app/upgrades/v530/upgrade.go

This PR adds the `v5.3.0` upgrade handler that also takes care of setting all validator's commission rate to the on-chain minimum, if it's lower than that.
---
I have...
I have...

feat: add v5.3.0 upgrade handler

---

.changeset/entries/43992e9f7a2a6ed33633e7cda8d69e2c0fb029abb0f90d99203f0718ae6ed613.yaml
app/wasm_config.go

Closes: #XXXX
This PR registers missing stargate queries for contract.
---
I have...
I have...

fix: register missing stargate queries for contract

---

.changeset/entries/7abfad6cf351c8e8f5f63d0fa55e57c0a1752f6ee4b6cf234229f640b8b26134.yaml
app/app.go
app/app_config.go
app/wasm_config.go
x/posts/abci.go
x/posts/keeper/common_test.go
x/posts/keeper/invariants.go
x/posts/keeper/keeper.go
x/posts/keeper/migrations.go
x/posts/keeper/msg_server.go
x/posts/module.go
x/posts/simulation/operations.go
x/posts/simulation/operations_attachments.go
x/posts/simulation/operations_polls.go
x/posts/simulation/operations_post_owner_transfer.go
x/posts/simulation/operations_posts.go
x/posts/wasm/common_test.go
x/posts/wasm/querier.go

This PR improves posts keeper input and output consistency.
---
I have...
I have...

refactor: improve posts keeper input/output consistency

---

x/posts/keeper/common_test.go
x/posts/keeper/genesis_test.go
x/posts/keeper/msg_server_test.go
x/profiles/keeper/common_test.go
x/reactions/keeper/common_test.go
x/relationships/keeper/common_test.go
x/reports/keeper/common_test.go
x/subspaces/ante/common_test.go
x/subspaces/ante/tx_checker_test.go
x/tokenfactory/keeper/common_test.go

This PR fixes the gomock controller finish by moving it to the `TearDownTest` phase, or it cannot find the missing calls of the function we setup on expected keepers.
It also fixes the tests having wrong setting on the expected keepers.
---
I have...
I have...

test: fix gomock controller finish

---

app/app_config.go

This PR disables the buggy wasm metrics in order to avoid node running failure.
Relates to https://github.com/CosmWasm/wasmd/issues/1574
---
I have...
I have...

fix: disable buggy wasm metrics

---

.changeset/entries/a11fd18cbf1a62ef72f896652407063fab25f8576b551025eaa9c8fc78aea5c2.yaml
x/profiles/keeper/msg_server_dtag_transfers.go

Closes: #XXXX
This PR fixes the issue that account has no account number since using `authtypes.NewBaseAccountWithAddress`. To solve it, we should use `AccountKeeper.NewAccountWithAddress` instead, to make sure account number is set.
---
I have...
I have...

fix: fix missing account number of account creation

---

docs/docs/02-developers/03-tools-to-build.md

Closes: #XXXX
This PR updates the docs of desmos-bindings part of `tools-to-build`, the current one is for v1.0.0 which is outdated.
---
I have...
I have...

docs: update contracts bindings docs

---

.changeset/entries/d3f03fad99e3c68e9114b638351cde7983870148f84626f49c69e2b52dc5abed.yaml
x/posts/keeper/msg_server.go
x/posts/keeper/msg_server_test.go
x/posts/types/events.go
x/profiles/keeper/msg_server_app_link.go
x/profiles/keeper/msg_server_app_link_test.go
x/profiles/keeper/msg_server_chain_link.go
x/profiles/keeper/msg_server_chain_link_test.go
x/profiles/keeper/msg_server_dtag_transfers.go
x/profiles/keeper/msg_server_dtag_transfers_test.go
x/profiles/keeper/msg_server_params.go
x/profiles/keeper/msg_server_params_test.go
x/profiles/keeper/msgs_server_profile.go
x/profiles/keeper/msgs_server_profile_test.go
x/profiles/types/events.go
x/reactions/keeper/msg_server.go
x/reactions/keeper/msg_server_test.go
x/reactions/types/events.go
x/relationships/keeper/msg_server.go
x/relationships/keeper/msg_server_test.go
x/relationships/types/events.go
x/reports/keeper/msg_server.go
x/reports/keeper/msg_server_test.go
x/reports/types/events.go
x/subspaces/keeper/msg_server.go
x/subspaces/keeper/msg_server_test.go
x/subspaces/types/events.go
x/tokenfactory/keeper/msg_server.go
x/tokenfactory/keeper/msg_server_test.go
x/tokenfactory/types/events.go

Currently, the `sdk.MessageEventType` is emitted twice in Desmos, it is because that cosmos-sdk already handles the default message type event.
As we can see, [the example transaction](https://testnet.bigdipper.live/desmos/transactions/F2340B9AFB6FF097085820B9F784251777FE43A700F0185E9542EF1AED914679) has two message type event:
```json
[
{
"events": [
{
"type": "message",
"attributes": [
{
"key": "action",
"value": "/desmos.posts.v3.MsgCreatePost"
},
{
"key": "sender",
"value": "desmos1q35n50xnlj7lapfkzzcq5rvypcvhure0rr945u"
}
]
},
{
"type": "message",
"attributes": [
{
"key": "module",
"value": "posts"
},
{
"key": "action",
"value": "/desmos.posts.v3.MsgCreatePost"
},
{
"key": "sender",
"value": "desmos1q35n50xnlj7lapfkzzcq5rvypcvhure0rr945u"
}
]
},
...skip
]
``` 
To fix it, we can …

fix: remove duplicated message type events

---

.changeset/entries/fde55b5ec55523b85ca6bdd056402412e261541152f06992879beff410ea45cc.yaml
go.mod
go.sum
x/posts/keeper/posts.go
x/posts/types/models.go
x/posts/types/models_test.go
x/reactions/keeper/reactions.go
x/reactions/types/models.go
x/reactions/types/models_test.go

This PR fixes how the text lengths related to a `Post` or a `FreeTextReactionValue` are computed. Previously the count would only consider the byte size of the text. Instead, it's much better to count graphemes. 
As per [this comment](https://stackoverflow.com/questions/36928185/counting-characters-in-golang-string#comment128023757_55148379): 
> There is a difference between bytes, runes, and graphemes, and it seems many people confuse the three. (In most use cases, it doesn't matter anyway.) For example, :rainbow_flag: (rainbow flag emoji) is 1 grapheme, 4 runes, and 14 bytes. The Go stdlib only has built-in functions for bytes and runes but not for graphemes.
By counting graphemes instead of runes or bytes, we can assure a consistent user experience with any application that implementes …

fix: text length not computed properly
